name: File Change Workflow

on:
  push:
    paths:
      - 'github_config/**'  # Trigger on changes in the github_config folder

jobs:
  print_file_names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print file names
        run: |
          # Get the list of changed files
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Print the names of changed files in the github_config folder
          echo "$changed_files" | grep '^github_config/'
