name: File Change Workflow

on:
  push:
    paths:
      - 'github_config/**'  # Trigger on changes in the github_config folder

jobs:
  print_file_names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print file names
        run: |
          # Get the list of file names in the github_config folder
          file_names=$(ls github_config)

          # Print the names of files in the github_config folder
          echo "$file_names"
